//! Handles the configuration of how documentation comments should be
//! generated by `doc-gen`.
//!
//! Documentation will likely be written in a TOML syntax and deserialized/validated
//! by serde.
//!
//! The intent is to write simple, yet robust configurations that can be validated
//! purely by the deserialization into the Rust type system.

/// The `DocConfig` will determine which nodes are included in the `DocTree`
/// as well as the style of documentation is generated for each `DocTree` node.
///
/// The `DocConfig` will also determine which documentation is required or optional
/// in order to pass `doc-gen --check`.
#[allow(unused)]
pub struct DocConfig;
